### ISSUE TITLE
contact_pair.has_any_active_contact() should be contact_pair.has_any_active_contacts() in the documentation?

### ISSUE THREAD

**Issue by Carter0** [dimforge/rapier.rs#101]
I'm on bevy_rapier_2d 13.1, and it wouldn't let me compile the program without making that method plural. The documentation on the website has it as "contact_pair.has_any_active_contact()". Also, the documentation in the rust docs doesn't mention that function at all, but does mention something called ContactPair::has_any_active_collider, which I am not sure exists?

**Comment by Vrixyz** [comment]
Thanks for the report, its *seems* to still be the case 🤔 ; a broken doc for 2 years is a good case for https://github.com/dimforge/rapier.rs/pull/99 !

**Comment by Vrixyz** [comment]
bevy side was fixed in #99 ; I'm working on fixing rust side now

**Comment by Vrixyz** [comment]
there is a shared part in the text, which prompts me to unify the api rather than fixing the docs: https://github.com/dimforge/bevy_rapier/pull/519 ; this will require a modification on the documentation for next release.
