### ISSUE TITLE
Add links to the the Bevy plugin's docs.rs under API Documentation

### ISSUE THREAD

**Issue by idanarye** [dimforge/rapier.rs#34]
The _API Documentation_ section in the side menu has links to the various flavors of the JavaScript APIs and to various flavors of the main Rapier APIs, but not to the Bevy plugin APIs ([`bevy_rapier2d`](https://docs.rs/bevy_rapier2d/) and [`bevy_rapier3d`](https://docs.rs/bevy_rapier3d/)). It would be helpful if you could add them.

**Comment by sebcrozet** [comment]
Thank you for the suggestion.
