### ISSUE TITLE
"Collision groups and solver groups" for bevy plugin is out of date

### ISSUE THREAD

**Issue by Breadp4ck** [dimforge/rapier.rs#75]
The corresponding [section](https://rapier.rs/docs/user_guides/bevy_plugin/colliders#collision-groups-and-solver-groups) of documentation is provided with out of date examples -- the code just does not compile.

```rust
// fails
// CollisionGroups::new(0b1101.into(), 0b0100.into());
// SolverGroups::new(0b0011.into(), 0b1011.into());

// ok
CollisionGroups::new(
    Group::from_bits(0b1101).unwrap(),
    Group::from_bits(0b0100).unwrap(),
);
SolverGroups::new(
    Group::from_bits(0b0011).unwrap(),
    Group::from_bits(0b1011).unwrap(),
);
```

**Comment by Vrixyz** [comment]
Thank again :) ; I'm closing this as it was merged ; it will be part of next website deployment (no planned date)
